In [1]:
import pandas as pd
import numpy as np
data=pd.read_csv(r"C:\Users\sairam\Downloads\eeg dataset\6controltestdataPLV_EO.csv")
#data.head()
#data.info()

data.isnull().sum()

data['Class'].value_counts()

from sklearn.preprocessing import LabelEncoder
enc=LabelEncoder()
data['Class']=enc.fit_transform(data['Class'])
data['Class'].value_counts()

cls_0=data[data['Class']==0]
cls_1=data[data['Class']==1]
cls_2=data[data['Class']==2]
cls_3=data[data['Class']==3]

cls_0=cls_0.sample(250,replace=True)
cls_1=cls_1.sample(250,replace=True)
cls_2=cls_2.sample(250,replace=True)
cls_3=cls_3.sample(250,replace=True)
data = pd.concat([cls_0,cls_1,cls_2,cls_3 ], axis=0)
#data.info()

corr=data.corr()

cor_target = abs(corr["Class"])
#Selecting highly correlated features
relevant_features = cor_target[cor_target>0.7]
relevant_features
#if needed use these features alone. These are highly correlated (only if u dont need to use all 450 columns)

y=data['Class']
X=data.drop(['Class'],axis=1)


from sklearn.model_selection import train_test_split

X_train,X_test ,y_train, y_test = train_test_split(X,y,
                                                   test_size=0.30,
                                                   random_state=0,
                                                  shuffle = True,
                                                  stratify = y)

print('training data shape is :{}.'.format(X_train.shape))
print('training label shape is :{}.'.format(y_train.shape))
print('testing data shape is :{}.'.format(X_test.shape))
print('testing label shape is :{}.'.format(y_test.shape))

from sklearn.svm import SVC
svc_model = SVC(kernel='rbf',gamma=8)
svc_model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, confusion_matrix
predictions= svc_model .predict(X_train)
percentage=svc_model.score(X_train,y_train)
res=confusion_matrix(y_train,predictions)
print("Training confusion matrix")
print(res)
predictions= svc_model .predict(X_test)
train_percentage=svc_model.score(X_train,y_train)
test_percentage=svc_model.score(X_test,y_test)
res=confusion_matrix(y_test,predictions)
print("Testing confusion matrix")
print(res)
# check the accuracy on the training set
print(svc_model.score(X_train, y_train))
print(svc_model.score(X_test, y_test))
print(f"Train set:{len(X_train)}")
print(f"Train Accuracy={train_percentage*100}%")
print(f"Test set:{len(X_test)}")
print(f"Test Accuracy={test_percentage*100}%")

training data shape is :(700, 85).
training label shape is :(700,).
testing data shape is :(300, 85).
testing label shape is :(300,).
Training confusion matrix
[[175   0   0   0]
 [  0 175   0   0]
 [  0   0 175   0]
 [  0   0   0 175]]
Testing confusion matrix
[[75  0  0  0]
 [ 0 75  0  0]
 [ 0  0 75  0]
 [ 0  0  0 75]]
1.0
1.0
Train set:700
Train Accuracy=100.0%
Test set:300
Test Accuracy=100.0%
